data:
  cluster_name: ""
  kubernetes_version: "1.36"
  coredns_version: "v1.11.4-eksbuild.14"
  kube_proxy_version: "v1.36.3-eksbuild.2"
  vpc_cni_version: "v1.24.0-eksbuild.1"
  ebs_csi_version: "v1.38.0-eksbuild.1"
  environment: "dev"
